version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  api:
    build: ./server
    ports:
      - "4000:4000"
    expose:
      - "4000"
    links:
      - mongo
    networks:
      - mern-app
    # env_file: ./server/config/${ENV}.env
  client:
    build: ./client
    ports:
      - "4300:80"
    networks:
      - mern-app
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
     - api
     - client
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data: 
   driver: local