version: "3.8"
services:
  api-server:
    image: api-server-local
    build: ./backend
    ports:
      - "4000:4000"
    env_file: ./backend/config/${ENV}.env
    # restart: unless-stopped
    # stdin_open: true
    # volumes:  ############# need to adjust the local and dist path
    #   - ./api-server:/app
  
  react-app:
    image: react-app-local
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    # restart: unless-stopped
    depends_on:
      - api-server
    # volumes:
    #   - ./api-server:/app

networks:
  mern-app:
    driver: bridge

